### ISSUE TITLE
Light casts shadow on itself

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#443] opened 2021-01-11 20:26 UTC
![image](https://user-images.githubusercontent.com/1578924/104234359-95f7dd00-5453-11eb-94bd-0f48cba3d33a.png)

![image](https://user-images.githubusercontent.com/1578924/104234408-a60fbc80-5453-11eb-8ca6-738eb322e844.png)

**Comment by niklas-ourmachinery** [comment] 2021-01-11 20:41
I can't reproduce this with just a light... I wonder if there is something else going on...

![image](https://user-images.githubusercontent.com/26548514/104235822-607ad180-540a-11eb-8a30-75df5689073f.png)

**Comment by Srekel** [comment] 2021-01-11 21:12
It didn't happen immediately. Not sure what happened to make it change. Perhaps the stream archive contains a clue.

**Comment by tobias-ourmachinery** [comment] 2021-01-14 11:04
All our default values are tweaked for a scene unit in Meters and your scene was imported in CM, so everything is 100x bigger than what we anticipate when setting ranges for things like the depth bias values for shadow mapping etc. 

So this isn't really a bug, it's the ground plane self shadowing due to the depth bias value being too low. You can try to increase the depth bias slider to max, it should help somewhat but it might still not be enough.

I will focus on making sure you can rescale geometry on import and close this as by-design for now.

**Closed by tobias-ourmachinery** 2021-01-14 11:04 UTC
Labels: by-design
