### ISSUE TITLE
Crash when simulating old sample

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#675] opened 2021-07-31 11:25 UTC
The Machinery 2021.7 is crashing 100% whenever I attempt to open the simulation tab, I've tested it in a few different sample projects. See attached minidmp below.

[the_machinery_exe 2021-07-31 13.17.27.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/6911086/the_machinery_exe.2021-07-31.13.17.27.dmp.zip)

**Comment by peterlindgren** [comment] 2021-07-31 11:30
After downloading new samples for 2021.7 it's working. I'm going to leave this issue open because I would expect TM to give me a warning/error of what's wrong with the (2021.6.b) sample.

**Comment by peterlindgren** [comment] 2021-07-31 11:34
I've updated the title accordingly. It might be a good idea to try opening all older (1.0 and beyond I suppose) samples and verify/fix any crashes.

**Comment by simonrenger** [comment] 2021-07-31 11:38
related to #669

**Comment by simon-ourmachinery** [comment] 2021-07-31 11:38
related to #669

**Comment by niklas-ourmachinery** [comment] 2021-08-02 17:39
The issue here is that our APIs are not stable and the old projects contain DLLs built against older APIs.

I think the right thing to do here is to introduce some versioning of the APIs. That way, when an older DLL runs it could detect that the APIs have changed and thus prevent itself from running (until it's recompiled).

So this will be fixed by fixing #671 .

**Comment by niklas-ourmachinery** [comment] 2021-08-06 16:43
Closing this as duplicate of #671 -- will track the work on this under that issue.

**Closed by niklas-ourmachinery** 2021-08-06 16:43 UTC
Labels: samples
