### ISSUE TITLE
Every time I delete a *.dcc_asset in the asset browser I seem to cause a crash.

### ISSUE THREAD

**Issue by photex** [OurMachinery/themachinery-public#742] opened 2021-08-24 20:20 UTC
Import one of the files I attached to #741 into a scene. Drag the asset into the world. Delete it from the world (using the outliner). Then select and delete the dcc_asset from the asset browser.

On my machine this is crashing reliably. Using 2021.7 and the latest on main in git as of earlier this afternoon.

Here is the dump from the last crash using 2021.7: 
[the_machinery_exe 2021-08-24 22.12.22.zip](https://github.com/OurMachinery/themachinery-public/files/7041895/the_machinery_exe.2021-08-24.22.12.22.zip)

**Comment by simon-ourmachinery** [comment] 2021-08-25 15:00
Cannot confirm the steps... maybe I am unsure what you mean by outliner.

**Comment by niklas-ourmachinery** [comment] 2021-08-25 15:57
The outliner would be the Entity Tree view, right?

**Comment by tobias-ourmachinery** [comment] 2021-11-29 11:29
Fixed in 2021.11, at least I can't reproduce it any more after some fixes related to not discovering dead truth objects in various places.

**Closed by tobias-ourmachinery** 2021-11-29 11:29 UTC
Labels: hard-to-reproduce
