### ISSUE TITLE
Editor crashes when changing resolution scale.

### ISSUE THREAD

**Issue by zargy** [OurMachinery/themachinery-public#602] opened 2021-07-08 21:11 UTC
In the provided clip, I try to change the resolution scale to 1.2, and this happens:

https://user-images.githubusercontent.com/1424508/124991158-eae16e00-e006-11eb-8527-8cf1871f56e4.mp4

It did not spit out a memory dump file for this specific crash.

**Comment by niklas-ourmachinery** [comment] 2021-07-08 21:54
Reproduced.

**Comment by niklas-ourmachinery** [comment] 2021-07-08 23:50
In addition to the crash, the UI for this is pretty bad... the value will update as you type which stalls the UI... it should probably wait with updating until the value is "committed".

**Comment by niklas-ourmachinery** [comment] 2021-07-09 00:13
Verified that the crash seems to be a bug in `tm_slab_remove_all()`. If replaced with a simple loop:

~~~c
for (struct ui_font *i = ui->fonts_slab; i != tm_slab_end(ui->fonts_slab); i = tm_slab_next(i)) {
    if (tm_slab_is_valid(i))
        tm_slab_remove(ui->fonts_slab, i);
}
~~~

the crash disappears. Will investigate further.

**Comment by zargy** [comment] 2021-07-09 12:13
👍 thanks for investigating!

**Comment by niklas-ourmachinery** [comment] 2021-07-09 13:50
https://github.com/OurMachinery/themachinery/pull/668

**Closed by niklas-ourmachinery** 2021-07-09 13:50 UTC

**Comment by niklas-ourmachinery** [comment] 2021-07-09 15:13
Also fixed so that the resolution doesn't update until you press return or tab to a different field.
