### ISSUE TITLE
Accessibility: low contrast of view labels in the dark theme

### ISSUE THREAD

**Issue by dominikdalek** [OurMachinery/themachinery-public#289] opened 2020-08-31 17:48 UTC
Gray on mustard yellow isn't very readable even for people with no vision impediments. The [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/) is a pretty good tool for checking contrast values with respect to accessibility.

**Comment by niklas-ourmachinery** [comment] 2020-08-31 17:53
Duplicate of #210.

**Comment by simon-ourmachinery** [comment] 2020-10-26 09:31
We have addressed the issue by now. Please check #210 for more details.

**Closed by simon-ourmachinery** 2020-10-26 09:31 UTC
Labels: design-decision
