### ISSUE TITLE
Custom component engine filter function uses three instead of two components

### ISSUE THREAD

**Issue by marot** [OurMachinery/themachinery-public#480] opened 2021-02-05 10:16 UTC
The `custom_component.c` code generated by adding a new `Entity Component` Plugin uses three components inside of the `engine_filter__custom_component` function, while only two (custom and transform) are registered.

**Comment by frank-ourmachinery** [comment] 2021-02-08 13:58
That used to be the Link Component, seems to be regression from when it was merged into the Transform Component. Fixed for next release.

**Closed by frank-ourmachinery** 2021-02-08 13:58 UTC
Labels: bug, minor
