### ISSUE TITLE
Support for resizing the top of Entity Graph Comments

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#998] opened 2022-02-04 08:20 UTC
As a user I would like to be able to resize the top of graph comments.
![resizing_the top_of_comments](https://user-images.githubusercontent.com/91697782/152495470-dc54bf24-3cb0-4a4d-9652-33a0a0addf43.gif)

**Comment by tobias-ourmachinery** [comment] 2022-02-07 09:09
This is by design, IIRC the reasoning behind it was to make sure you don't accidentally resize the comment box instead of moving it (ping @karl-zylinski-ourmachinery -- close this issue if you still stand behind the decision :)).

**Note that you can move the top by grabbing the top left corner.**

**Closed** 2022-02-17 14:19 UTC
Labels: enhancement
