### ISSUE TITLE
Grey wire appear when using the "for" node in entity graphs

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1352] opened 2022-05-27 09:08 UTC
- **Version:** Git Master Branch
- **OS:** Windows

Repro project:
[ForNodeGreyWire.zip](https://github.com/OurMachinery/themachinery-public/files/8785443/ForNodeGreyWire.zip)

Open the project above and open the "subbie.entity_graph" from the asset browser.
Note the grey wire into the ***input*** floating point connector called "End" of the "for" node

If you remove the ***output*** wire from the "End" event connector of the "for" node the input wire will become white again. And if you re-add the output wire (either by undo or manual creation) then the output wire will become grey.

Also note that the grey wires doesn't work. I.e when the input wire is grey, the output will be "0, apa" so the loop only ran one iteration, and when the output wire is grey the output will be "0, 1, 2" so the loop ran three iterations but the end event wasn't fired.

**Comment by karl-zylinski-ourmachinery** [comment] 2022-05-30 12:41
Fixed in https://github.com/OurMachinery/themachinery/commit/18be0dd8b5d368d0ef0ff7e206104e36c935a868

It was due to the For node having two connectors named 'end' and some buggy code that handles conflicts caused by adding new connections in inheritance hierarchies of graphs.

**Closed by karl-zylinski-ourmachinery** 2022-05-30 12:41 UTC
