### ISSUE TITLE
Editor font rendering slightly blury

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#639] opened 2021-07-19 06:52 UTC
![image](https://user-images.githubusercontent.com/108040/126115247-007d0d1b-77b7-4113-aeee-73293c2ba37a.png)

The fonts are slightly blury, just enough to make it uncomfortable on my eyes. It's quite subtle, but noticable on the T's "bar".  

Using an AMD 5700XT GPU

**Comment by LaylBongers** [comment] 2021-07-23 12:35
This topic came up on the discord. I've got a few notes on this issue:

What seems to be happening is that 'font hinting' is properly made use of, this is a common issue with stb_truetype that will not be fixed as it's considered too complex for the use cases of the library.
See: https://github.com/nothings/stb/issues/481#issuecomment-324319790

Switching to something like FreeType for the editor's font rendering would significantly improve this issue, as FreeType does implement font hinting correctly. Since recently the GTK team has been working hard on making GTK and its dependencies FreeType and HarfBuzz (text shaping engine) compileable natively on VS2019, which makes embedding this now much easier than it has been in the past.

Besides using FreeType + HarfBuzz (it's good practice to use both as HarfBuzz supports weird Unicode formatting very well), it would also be possible to fall back to the system's font renderer. Most software tends to use this approach for UIs. Windows' font renderer is particularly good at small sizes.

Another alternative would be something like Pathfinder (used by the Servo browser engine), which supports very high quality font rendering, but doesn't including support for more advanced text shaping.

**Comment by LaylBongers** [comment] 2021-07-28 12:49
A few more notes from the discord:

I rendered a series of "l" characters using `glyphs` - `draw_glyphs`:

![mspaint_UnsS8TJcYF](https://user-images.githubusercontent.com/3094382/127323196-5e5b24c6-b257-44bf-9136-f164bcf44371.png)

From my understanding, The Machinery uses a rasterized glyph cache for fonts. This is a very fast but also low quality method of rendering fonts, and when glyphs are rendered off-grid like above it reduces quality further.

One improvement would be to specify font height in pixels rather than points. "points" as a measurement is relative to inches and will result in glyphs rendered with heights not well aligned with the pixel grid. Using pixels instead is recommended anyways by the `stb_truetype` docs:

![firefox_o29NK0foUf](https://user-images.githubusercontent.com/3094382/127323608-1d471fd5-a6d7-4160-bbbf-7fcf7c214e2c.png)

Pixels is also the standard in most contexts now, including web where font sizes are represented generally in a base pixel size + a size relative to that. (root pixel size + rem sizes)

Beyond these individual points, here's VSCode rendering the same test:

![mspaint_bv9GeO2WPG](https://user-images.githubusercontent.com/3094382/127323931-ec5d7f1d-549a-4b6f-9047-ffe816588a3b.png)

VSCode uses Chromium which IIRC uses the system font renderer (probably GDI+ or DirectWrite on windows). However rather than using a glyph cache, it renders and caches individual strings. This is common for rendering UIs, as it's the only way to properly do sub-pixel anti-aliasing and kerning correctly. Glyph caches are more appropriate for rendering text dynamically in 3D, where these features aren't easily possible anyways.

A good reference may be Firefox WebRender's rendering API, as they use a system somewhat similar to immediate-mode. They re-render the entire page every frame using a command buffer style API, and this includes text rendering which is cached on-demand. (last I checked at least, this may be outdated by now)

**Comment by tobias-ourmachinery** [comment] 2021-07-28 14:11
I'm aware of the problems with using cached glyph charts and I do agree that there's stuff that can be done to increase sharpness for small text rendering, where hinting and [subpixel rendering](https://en.wikipedia.org/wiki/Subpixel_rendering) could be two things worth exploring. 

Worth noting though is that we have lots of places where we need really high-performance subpixel placement of text (including rotation and zooming) so just falling back to rely on some existing high-quality software rasterizer that supports hinting is probably not the way to go. 

"Font hinting" is likely never going to be something we try to implement ourselves, while subpixel rendering might be worth exploring as that sounds fairly straightforward to implement. We'll see when we get there. Right now its pretty low on the priority list, especially considering more and more people running on high-dpi screens where this is less of a problem.

With that said, the initial reported blurriness has been bothering me for quite some time as it has felt like it shouldn't become *that* bad. After a bunch of digging I realized that our UV calculations were off by half a pixel caused by the oversampling used in the glyph cache. That's now been fixed and will be part of the July release. 

![image](https://user-images.githubusercontent.com/26548681/127334849-875a8edc-a6f0-4783-b4e6-05f7dda699b2.png)

Screenshot shows menu bar after the fix.

**Closed by tobias-ourmachinery** 2021-07-28 14:11 UTC

**Comment by LennardF1989** [comment] 2021-08-19 19:00
Is this supposed to be fixed for .7? Because I still have this issue in that version.
