### ISSUE TITLE
Crash while dragging dcc_asset into scene then moving entity in tree

### ISSUE THREAD

**Issue by sY9sE33** [OurMachinery/themachinery-public#112] opened 2020-02-14 00:02 UTC
Steps to reproduce:

1. Import mesh into asset browser (e.g. a plane)
2. place in scene in an entity which is a child of the root entity (EntityA)
3. import second mesh (e.g. a cube) into asset browser
4. drag new asset (EntityB) from the asset browser onto the existing asset so that it is added as a new entity which is a child of the previous entity (EntityB is a child of EntityA)
5. drag (in the entity tree view) the new entity (EntityB) to make it a child of the root entity
6. crash

**Comment by niklas-ourmachinery** [comment] 2020-02-14 00:24
Could not reproduce... I know I fixed some stuff related to dragging and dropping, so this might have been fixed already:

http://youtu.be/xMPjHftUuq4?hd=1

Closing for now... try it in the next version and see if it still crashes... or check my repro video and see if you're doing something different.

**Closed by niklas-ourmachinery** 2020-02-14 00:24 UTC

**Comment by sY9sE33** [comment] 2020-02-14 00:42
I achieved it with a slightly different flow, but I'll definitely try it again in the new build. I've attached the steps that I take to get it to crash:

![machinery_crash](https://user-images.githubusercontent.com/9271353/74491120-ba8cb300-4e98-11ea-88c1-79d9390a60da.gif)

There may also be a bug with the directional lights in that it doesn't seem to cast light until I rotate it (as seen in the gif) but I haven't played around with it enough to say one way or another.

**Comment by niklas-ourmachinery** [comment] 2020-02-15 03:20
Let me try that flow.

As for the directional light -- the problem is that in the default rotation, the light is cast parallel to the plane so it won't actually hit it. That's why you don't see it until you rotate the entity. It's a bit confusing the first time you run into it... but I can't think of a good way to address it. I don't want to change the axis the directional light is cast along, since we use the same "look at" axis for everything. It also doesn't make sense to rotate the entity when you add the directional light just so you can see the light better.

Maybe some better debug visualization of directional lights would help.

**Comment by sY9sE33** [comment] 2020-02-15 16:22
Yeah, I would definitely agree that the lighting is not a bug and that giving it a rotation other than the current one isn't appropriate as a fix. I think perhaps something like a large icon (maybe that scales with the display so that it's always the same size no matter how close one is) plus the direction of the light always being displayed would go a long way in terms of UX for them.
