### ISSUE TITLE
Error message when opening gameplay-third-person project

### ISSUE THREAD

**Issue by InjaEm** [OurMachinery/themachinery-public#241] opened 2020-06-02 20:30 UTC
When I opened the gameplay-third-person example code, I see 3 error messages immediately.

All three point to one "missing" path that does not exist on my computer.

Here is a picture ...

![tm-example-error](https://user-images.githubusercontent.com/66333818/83566579-3e24eb00-a4ee-11ea-864c-8687caad0d3b.png)

**Comment by niklas-ourmachinery** [comment] 2020-06-03 14:41
The paths specify which source file on the build machine that caused the problem, so it is expected that you don't have the path.

I tried to reproduce your problem:

1. Started `the-machinery.exe` from the `beta-2020-5.a` build.
2. Opened `gameplay-third-person.the_machinery` from `sample-projects-2020.5.a`.

This did not reproduce the error messages you are seeing.

Did you do any modifications to the project? Are you using `2020.5.a` for both the project and the data? Do you still get the error messages if you repeat my steps?

Although annyoing, these error messages do not indicate anything dangerous, so you should still be able to use all of *The Machinery*... I would like to find the root cause and get rid of the though.

**Comment by InjaEm** [comment] 2020-06-03 18:57
All I did was install your program for the first time and loaded it. It was the first time I used it. No modifications were made.

**Comment by niklas-ourmachinery** [comment] 2020-06-03 20:23
Ah, that is probably the reason. The 2020.5.a release is available for download on the forum. Here's the link:

https://forums.ourmachinery.com/t/beta-release-may-2020/980/4

**Comment by niklas-ourmachinery** [comment] 2020-06-08 15:25
Closing this on @InjaEm's request since it was reported for an old version.

**Closed by niklas-ourmachinery** 2020-06-08 15:25 UTC
