### ISSUE TITLE
Networking Graph Poll Key Pressed/Release do not work correctly

### ISSUE THREAD

**Issue by RiederAlex** [OurMachinery/themachinery-public#917] opened 2021-12-17 11:21 UTC
How to reproduce:
Create the graph attached
Launch server & client
Press & Release 'P' on the server will print "P!" and "P REL!" once
Press & Release 'P' on the client will spam "P!" and P REL!" multiple times

I've also tested it with "Poll Key for Entity"-Node with correct ownership, which behaves the same.
![issue](https://user-images.githubusercontent.com/14026803/146537089-b3bcc9a1-cf3e-4c62-814a-6783744463b5.PNG)

Version: 9f593b37a4b5eb2a72c15a1a740e9daf3aa550c3

**Comment by leonardo-ourmachinery** [comment] 2021-12-17 12:15
Assuming that your Server instance is flagged with "Update when Hidden", and that with "multiple times" you mean "Two", then what I would say this is the intented behavior:

-In the "Poll Key" case, when you're focusing on the Client, your server's graph is actually running "behind the scenes", and so when you press the button the log is printed for the server as well.

-In the "Poll Key For Entity" case, the same thing happens only that the server is using the input that came from the client instead of the "hardware" input, but it's the same concept.

Removing the "Update when Hidden" flag should give you the result you're expecting, but then your Server won't be updated if you have two simulate tabs in the same window and the server's one is hidden. This is not generally what you want though, your server should always be updated no matter if it's in focus or not. (It's what you almost certainly want for your server when you actually ship it, so I think it's good to be able to reproduce that situation in the editor as well).

Still, I should probably make it so that the "log" node also prints the name of the instance that was responsible for prodicing it if there are multiple, to makes things a bit clearer.

**Comment by RiederAlex** [comment] 2021-12-17 12:32
Ah my fault that I was not completely clear in the initial description: With multiple times I mean "It spams the log output"
So after pressing 'P' once in the client window my console output looks like this

![image](https://user-images.githubusercontent.com/14026803/146545110-1fb024ab-3700-491a-9c2f-4d1fb380aee5.png)

**Comment by leonardo-ourmachinery** [comment] 2021-12-17 12:42
That doesn't look like well-behaving networking code. 
I'm looking into it, I hope you're not super blocked by this.

**Comment by leonardo-ourmachinery** [comment] 2021-12-17 16:22
Fixed in master with: https://github.com/OurMachinery/themachinery/commit/2fb8ca75cb238232e30a36415cbda19d5f78694c

Note that input is completely disabled for tabs that are not in focus, so I actually said something wrong in the previous comment: your Server won't Poll the input when the focus is on the Client window, even if you've flagged it with the "Update when hidden" Flag.

In the second case you will instead see the pressed/released events two times (one for the client and one for the server) because the "Remote Input" that the server gets from the client is not disabled, even if the server is not in focus.

**Closed by leonardo-ourmachinery** 2021-12-17 16:22 UTC
