### ISSUE TITLE
Third Person Demo: Simulation restart causes crash or missing geometry in render 

### ISSUE THREAD

**Issue by MasonRemaley** [OurMachinery/themachinery-public#221] opened 2020-05-10 02:44 UTC
I'm guessing these are actually two separate bugs (maybe an imgui problem and a culling problem? unsure.)

What happened:
- Launched the first person demo
- Added a simulation tab, toyed around with a few things
- Ran the third person demo
- Ran a couple laps collecting the pickups
- Walked off the edge of the map and let my character fall for a while
- Pressed the restart button in simulation
- Got the following error message, twice:
```
The application encountered a fatal error and needs to be shut down. If this error occurred during bootup, try updating your GPU drivers. Otherwise, report this error together with crash dumps and logs from AppData\Local\{Application Name}.

C:\work\themachinery\plugins\statistics\statistics_source.c:226

t->num_open_scopes < MAX_OPEN_SCOPES
```

Unfortunately, I had not yet set up the registry settings so I don't have the crash logs. I can no longer repro the crash, but instead I can consistently cause this to happen:

- Launch The Machinery
- Open the third person demo from the recent menu
- Add a simulation tab
- Walk off the edge of the map
- Click the restart button
- Most of the level geometry is now missing from the render, although it shows up in the scene tab and still affects physics. The green pickup is not rendered but I can see where it is because of the light, if I get it the new one is rendered as normal.
- If I click restart *without* jumping off the ledge, everything comes back

[EDIT] (Happy to provide details about my machine etc if that would help recreate)

**Comment by niklas-ourmachinery** [comment] 2020-05-11 14:05
Yes, these are separate bugs.

The first bug is caused by profiling scopes not being properly closed. I can't fix this without knowing exactly which profiling scope is at fault (it might already have been fixed). But I've fixed so that this is no longer a fatal error. Instead it will just print an error message that can help us fix it without a full crash dump.

**Comment by niklas-ourmachinery** [comment] 2020-05-11 14:21
I reproduced your second bug in our latest build.

In my reproduction the green pickup was drawn as a "mesh monster".

@tobias-ourmachinery This seems to be a rendering issue, so assigning to you.

**Comment by MasonRemaley** [comment] 2020-05-11 18:08
Awesome, glad you were able to reproduce the rendering problem! If I happen to hit the profiler bug again while testing out other stuff I'll update the issue.

**Comment by tobias-ourmachinery** [comment] 2020-05-12 13:15
Rendering corruption / mesh monster fixed.

**Closed by tobias-ourmachinery** 2020-05-12 13:15 UTC
