### ISSUE TITLE
game play third person sample from  2021.6.b  causes crash after updating to 2021.7

### ISSUE THREAD

**Issue by creadmefford** [OurMachinery/themachinery-public#669] opened 2021-07-30 15:45 UTC
- launched 2021.6.b and it indicated a new build was available so I downloaded it.
- next launched 2021.7 which crashes after trying to load a sample that I was playing with from 2021.6.b.
- on a second launch of 2021.7 it recognizes the previous launch failure and gives me two options: recover or discard changes.  both options cause a crash.

see attached screenshot and dumps

[dumps.zip](https://github.com/OurMachinery/themachinery-public/files/6908622/dumps.zip)
![image](https://user-images.githubusercontent.com/976243/127677729-854e039e-7121-4f0d-a9c4-34e18c7b393b.png)

**Comment by simonrenger** [comment] 2021-07-30 19:20
This is unfortunate but this can happen between versions. This is why we recommend always use the latest version of the samples. Never the less we will investigate the issue.

**Comment by simon-ourmachinery** [comment] 2021-07-30 19:21
This is very unfortunated but this can be expected when switching versions. There for it is always good to use the latest version of the samples as well. Never the less we will investigate your issue.

**Comment by simon-ourmachinery** [comment] 2021-07-30 19:24
You can delete the last used file by `C:\Users\user\AppData\Local\The Machinery` and remove it from the `settings.json` `recent_files`. You can also start the engine `--safe-mode` or `In addition to using the `--safe-mode` flag, you can also start in safe mode\n by holding F8 while The Machinery is booting up`

**Comment by niklas-ourmachinery** [comment] 2021-08-02 17:42
I assume this is the same issue as #675 . Did you have the simulation tab open?

Using Simon's instruction for starting in Safe Mode should get you up and running and running the newer samples should fix it.

**Comment by creadmefford** [comment] 2021-08-03 23:45
thanks for investigating. the simulation tab was probably open. my goal was just to launch the 2021.7 editor and try out the latest.  i worked around the issue by deleting the 2021.6.b samples.  the --safe-mode options will work great in the future.  thanks!

**Comment by niklas-ourmachinery** [comment] 2021-08-06 16:43
Closing this as duplicate of #671 -- will track the work on this under that issue.

**Closed by niklas-ourmachinery** 2021-08-06 16:43 UTC
Labels: crash, samples
