### ISSUE TITLE
API versioning and validation

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#671] opened 2021-07-30 16:15 UTC
Plugins currently load regardless of API compatibility. Giving APIs versions would allow plugins to verify dependencies. This would also make it easier to deprecate APIs long-term, by specifying breaking changes in a way that can be verified programmatically.

My suggestion for this is to give APIs an option to report the version when registered. A good standard to follow is [Semantic Versioning](https://semver.org/), which provides a well understood pattern for reporting breaking changes:

- Major version bump on breaking change (2.0.0 -> 3.0.0)
- Minor version bump on new features or APIs marked for deprecation but still accessible (2.0.0 -> 2.1.0)
- Patch version bump on bugfixes (2.0.0 -> 2.0.1)

Also commonly added and used by most tooling:
- For pre-release versions, marked with a 0 major version, minor denotes breaking changes. (0.1.0 -> 0.2.0)

When requesting an API, the plugin can then specify what version it requires, and by semver rules this can be verified.

As an additional benefit, allowing plugins to submit *multiple versions* of the same API lets plugins deprecate old functionality gradually while still providing it.

**Comment by LaylBongers** [comment] 2021-08-02 16:53
As an additional note on this:
Introducing this would allow a granular 'stabilization' of APIs. Any API that's still somewhat in flux in the public interface would be marked with a pre-1.0 version. In semver this communicates that the public API is very likely to change and require updating.

**Comment by niklas-ourmachinery** [comment] 2021-08-06 17:45
I've implemented a partial fix for the issues caused by this: The editor will now switch to Safe Mode if the last execution crashed. This prevents you from getting stuck in a loop where the editor continuously crashes because it tries to reopen the last opened project and restore the Simulation tab that crashed.

I agree that versioning the APIs is desirable, but I have to think a little more about the design of this.

**Comment by leonardo-ourmachinery** [comment] 2021-08-10 14:24
Me and @niklas-ourmachinery talked about this one before.

I personally think that plugin developers should just care about one thing when pushing a new "version" of their plugin to an ideal "plugin server":
Does the plugin version I'm pushing break forward compatibility with the previous version?

Then, if the answer to the question is no, the plugin can be immediately downloaded by all users, otherwise they will receive some kind of notification and the version number will be bumped automatically by the "plugin server", and the behavior you describe will happen at runtime in the same exact way.

I personally don't think having a plugin that exposes multiple versions of the same plugin for "gradually deprecating API's" is useful, as:
-developers that are developing game in production will most likely want to stay on the "stable" version and delay the update to their next project anyway.
-developers that are in "exploration" mode probably won't mind fixing errors in their plugins, and if they do they can just reject or postpone the update.

On top of all of this, it would be very nice to have a program that helps the developer detects if an header file is forward compatible with another one.

**Comment by LaylBongers** [comment] 2021-08-10 17:38
My suggestion for API versioning is for versioning APIs available in the registry, not plugin DLLs.
This suggested versioning scheme would also apply to APIs distributed as part of The Machinery itself (such as the truth, UI, entities, etc).

Though plugin DLLs being versioned has its own benefits, that's unrelated to this issue.

> developers that are developing game in production will most likely want to stay on the "stable" version and delay the update to their next project anyway.

This is increasingly not the case, especially in the indie space where developers may stick to an off the shelf engine for the same game for up to a decade, continually updating. Unity is especially notorious on this issue, and it's not uncommon for version updates to be a significant amount of work because of the lack of a decent migration scheme.

Including API versioning like this would allow breaking API changes to be introduced, while still allowing plugins to load in the old API version if still provided (made available for compatibility for a duration), without even a recompile needed.

An additional issue is that third party plugin authors will also want to continue to support new versions and old versions at the same time. Having dynamic API versioning following a scheme like this would make it easy to distribute one DLL that can support multiple versions, by detecting available features from the reported version.

**Comment by niklas-ourmachinery** [comment] 2021-08-11 16:24
I think a plugin should at least have the option of offering multiple versions of its API -- and then it's up to the plugin developer if they want to make use of that or not.

It's easy to end up in "version hell" where you want to upgrade one plugin to fix a bug... but you can't, because that requires you to upgrade your engine and one of your other plugins doesn't work with the new version of the engine. Allowing plugins to provide and work with multiple versions of other plugins can mitigate this situation. Again... it's a bunch of work to maintain and test multiple versions... so I'm not sure it's something that people will want to do... but they should at least have the option.

I'd like to introduce plugin versioning gradually in an opt-in way, such that if you don't provide a version to `set()` or `get()`, it just uses the current engine version at compile time.

This way, if you don't provide explicit versioning, your plugin is assumed to just work with the engine version it was compiled for. And if you try to use the plugin with a different engine version, you will get an error message. So by default, plugins are assumed to be in "constant flux" -- changing with every engine version.

This always you to introduce versioning on a plugin-by-plugin basis as each plugin gets "stabilized".

But we also need a way of versioning the API registry itself... which is what I'm thinking about at the moment.

**Comment by LaylBongers** [comment] 2021-08-11 17:25
> I'd like to introduce plugin versioning gradually in an opt-in way, such that if you don't provide a version to set() or get(), it just uses the current engine version at compile time.

I think it may be a good idea to require a version for `get()` and `set()` regardless. It's not a huge effort to add a semver string for the plugin author, and any non-breaking changes should be compatible anyways. The version string is considered a minimal requirement by the semver standard by default.

For example, a plugin may select truth version 1.2.0:

```
registry->get(TM_THE_TRUTH_API_NAME, "1.2.0");
```

This would specify that this plugin depends on "at least version 1.2.0".
A plugin developer could still specify "*" to get what-ever's latest available.

In the situation where the engine may update the version to, for example, `1.3.0` to provide new features, the version will still match (as minor version increases are considered backwards compatible).

If the engine does make a breaking change (marking the new API `2.0.0`), it would allow the mismatch to be detected. It also allows the plugin to specify a `get_optional` for the new API while still supporting the old API as well.

Some other possible semver version string examples:
- `0.1.0`: Matches 0.1.0, 0.1.5, but not 0.2.0
- `^1.2.0`: Explicitly matches "1.2.0 or higher compatible"
- `<=1.2.0`: Matches 1.2.0 or any lower version
- `*`: Matches any version

**Comment by niklas-ourmachinery** [comment] 2021-09-09 19:47
A versioning system is in the engine now and will be released with 2021.9:

* It uses the semver versioning model.
* A macro call `tm_os_api = tm_get_api(reg, tm_os_api);` gets the latest version of the API _when the plugin is compiled_. (This is usually what you want.)
* You can get an older version by asking for it: `tm_my_api_v10 = tm_get_old_api_version(reg, tm_my_api_v10);`.
* A plugin can choose to export multiple versions of an API.
* If a plugin cannot fulfil its dependencies, an error message will be printed and the plugin will be unloaded.

We don't support any advanced version queries as in your example and I don't think we really need to. Since our distribution model is pre-built ABIs rather than source code that you compile on your own, there will only be a small number of versions available (most likely just one or two) and picking a non-compatible version (different major number) is almost 100 % guaranteed to crash.

**Closed by niklas-ourmachinery** 2021-09-09 19:47 UTC
Labels: enhancement, design-decision
