### ISSUE TITLE
Scroll wheel on drop-down lists of available choices

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1039] opened 2022-02-14 10:53 UTC
In some nodes I get to open a drop-down menu and select options.

Examples:
- spawn entity
- poll key
- get/set properties
- add/remove tag
and more.

A list of a certain length appears. 
Sometimes it is too long for how far I am zoomed in so I don't see the list. 
Sometimes the length of the list is too short to tell me what all the available options are.

Adding a dynamic size that turns into a scroll bar on these drop-down lists would be really great.

**Comment by simon-ourmachinery** [comment] 2022-02-14 11:03
Duplicate of: #891 and #703

**Comment by frank-ourmachinery** [comment] 2022-06-02 06:08
The popup item pickers (dropdowns) now have scrolling functionality. See #891 for an example of this behaviour.

**Closed by frank-ourmachinery** 2022-06-02 06:08 UTC
Labels: enhancement
