### ISSUE TITLE
Crash during 2021.1 start up

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#476] opened 2021-01-31 13:51 UTC
While starting up a 2021.1 clean install, it crashes before completing start up with the following dump and log.

Latest GPU drivers and Windows updates.

----

**Dump:**  [the_machinery_exe 2021-01-31 10.42.10.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/5899833/the_machinery_exe.2021-01-31.10.42.10.dmp.zip)
**Log:**
```
λ the-machinery.exe --safe-mode

The Machinery - Version 2021.1 [SAFE MODE]
Number of available instance layers: 9
    VK_LAYER_AMD_switchable_graphics (Description: AMD switchable graphics layer)
    VK_LAYER_RENDERDOC_Capture (Description: Debugging capture layer for RenderDoc)
    VK_LAYER_VALVE_steam_overlay (Description: Steam Overlay Layer)
    VK_LAYER_VALVE_steam_fossilize (Description: Steam Pipeline Caching Layer)
    VK_LAYER_EOS_Overlay (Description: Vulkan overlay layer for Epic Online Services)
    VK_LAYER_EOS_Overlay (Description: Vulkan overlay layer for Epic Online Services)
    VK_LAYER_OBS_HOOK (Description: Open Broadcaster Software hook)
    VK_LAYER_OBS_HOOK (Description: Open Broadcaster Software hook)
    VK_LAYER_ROCKSTAR_GAMES_social_club (Description: Rockstar Games Social Club Layer)

Number of available instance extensions: 11
    VK_KHR_device_group_creation
    VK_KHR_external_fence_capabilities
    VK_KHR_external_memory_capabilities
    VK_KHR_external_semaphore_capabilities
    VK_KHR_get_physical_device_properties2
    VK_KHR_get_surface_capabilities2
    VK_KHR_surface
    VK_KHR_win32_surface
    VK_EXT_debug_report
    VK_EXT_debug_utils
    VK_EXT_swapchain_colorspace

Number of physical devices: 1
Device: 0 Name: AMD Radeon RX 5700 XT (Discrete GPU)
    Vendor ID: 1002 Device ID: 731f
    Raw Driver Version: 8388776
    Supported Vulkan Version: 1.2.159

    Number of available device layers: 2
        VK_LAYER_AMD_switchable_graphics (Description: AMD switchable graphics layer)
        VK_LAYER_OBS_HOOK (Description: Open Broadcaster Software hook)

    Number of available device extensions: 107
        VK_KHR_16bit_storage
        VK_KHR_8bit_storage
        VK_KHR_bind_memory2
        VK_KHR_buffer_device_address
        VK_KHR_create_renderpass2
        VK_KHR_dedicated_allocation
        VK_KHR_depth_stencil_resolve
        VK_KHR_descriptor_update_template
        VK_KHR_device_group
        VK_KHR_draw_indirect_count
        VK_KHR_driver_properties
        VK_KHR_external_fence
        VK_KHR_external_fence_win32
        VK_KHR_external_memory
        VK_KHR_external_memory_win32
        VK_KHR_external_semaphore
        VK_KHR_external_semaphore_win32
        VK_KHR_get_memory_requirements2
        VK_KHR_imageless_framebuffer
        VK_KHR_image_format_list
        VK_KHR_maintenance1
        VK_KHR_maintenance2
        VK_KHR_maintenance3
        VK_KHR_multiview
        VK_KHR_pipeline_executable_properties
        VK_KHR_relaxed_block_layout
        VK_KHR_sampler_mirror_clamp_to_edge
        VK_KHR_separate_depth_stencil_layouts
        VK_KHR_shader_atomic_int64
        VK_KHR_shader_clock
        VK_KHR_shader_draw_parameters
        VK_KHR_shader_float16_int8
        VK_KHR_shader_float_controls
        VK_KHR_shader_non_semantic_info
        VK_KHR_shader_subgroup_extended_types
        VK_KHR_shader_terminate_invocation
        VK_KHR_spirv_1_4
        VK_KHR_storage_buffer_storage_class
        VK_KHR_swapchain
        VK_KHR_swapchain_mutable_format
        VK_KHR_timeline_semaphore
        VK_KHR_uniform_buffer_standard_layout
        VK_KHR_variable_pointers
        VK_KHR_vulkan_memory_model
        VK_KHR_win32_keyed_mutex
        VK_EXT_calibrated_timestamps
        VK_EXT_conservative_rasterization
        VK_EXT_depth_clip_enable
        VK_EXT_depth_range_unrestricted
        VK_EXT_descriptor_indexing
        VK_EXT_extended_dynamic_state
        VK_EXT_external_memory_host
        VK_EXT_full_screen_exclusive
        VK_EXT_global_priority
        VK_EXT_hdr_metadata
        VK_EXT_host_query_reset
        VK_EXT_image_robustness
        VK_EXT_inline_uniform_block
        VK_EXT_line_rasterization
        VK_EXT_memory_budget
        VK_EXT_memory_priority
        VK_EXT_pipeline_creation_cache_control
        VK_EXT_pipeline_creation_feedback
        VK_EXT_post_depth_coverage
        VK_EXT_private_data
        VK_EXT_queue_family_foreign
        VK_EXT_robustness2
        VK_EXT_sampler_filter_minmax
        VK_EXT_sample_locations
        VK_EXT_scalar_block_layout
        VK_EXT_separate_stencil_usage
        VK_EXT_shader_demote_to_helper_invocation
        VK_EXT_shader_image_atomic_int64
        VK_EXT_shader_stencil_export
        VK_EXT_shader_subgroup_ballot
        VK_EXT_shader_subgroup_vote
        VK_EXT_shader_viewport_index_layer
        VK_EXT_subgroup_size_control
        VK_EXT_texel_buffer_alignment
        VK_EXT_tooling_info
        VK_EXT_transform_feedback
        VK_EXT_vertex_attribute_divisor
        VK_AMD_buffer_marker
        VK_AMD_calibrated_timestamps
        VK_AMD_device_coherent_memory
        VK_AMD_display_native_hdr
        VK_AMD_draw_indirect_count
        VK_AMD_gcn_shader
        VK_AMD_gpa_interface
        VK_AMD_gpu_shader_half_float
        VK_AMD_gpu_shader_int16
        VK_AMD_memory_overallocation_behavior
        VK_AMD_mixed_attachment_samples
        VK_AMD_pipeline_compiler_control
        VK_AMD_shader_ballot
        VK_AMD_shader_core_properties
        VK_AMD_shader_core_properties2
        VK_AMD_shader_explicit_vertex_parameter
        VK_AMD_shader_fragment_mask
        VK_AMD_shader_image_load_store_lod
        VK_AMD_shader_info
        VK_AMD_shader_trinary_minmax
        VK_AMD_texture_gather_bias_lod
        VK_AMD_wave_limits
        VK_GOOGLE_decorate_string
        VK_GOOGLE_hlsl_functionality1
        VK_GOOGLE_user_type

Number of device groups: 1
    Device Group: 0 Number of physical devices: 1 Supports subset allocation: false
        Physical available_device: 0 Name: AMD Radeon RX 5700 XT (Discrete GPU)

Hardware accelerated ray tracing is not supported.
Missing features:
    bufferDeviceAddress
    bufferDeviceAddressMultiDevice

```

**Comment by khskarl** [comment] 2021-01-31 14:05
End of the log using `--vulkan-validation`, everything else is the same.
```
...
        VK_AMD_shader_trinary_minmax
        VK_AMD_texture_gather_bias_lod
        VK_AMD_wave_limits
        VK_GOOGLE_decorate_string
        VK_GOOGLE_hlsl_functionality1
        VK_GOOGLE_user_type

VUID-VkPhysicalDeviceGroupProperties-sType-sType
Validation Error: [ VUID-VkPhysicalDeviceGroupProperties-sType-sType ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xc9edee8b | vkEnumeratePhysicalDeviceGroups: parameter pPhysicalDeviceGroupProperties[0].sType must be VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkPhysicalDeviceGroupProperties-sType-sType)
VUID-VkPhysicalDeviceGroupProperties-pNext-pNext
Validation Error: [ VUID-VkPhysicalDeviceGroupProperties-pNext-pNext ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf7a24f8d | vkEnumeratePhysicalDeviceGroups: value of pPhysicalDeviceGroupProperties[0].pNext must be NULL. This error is based on the Valid Usage documentation for version 162 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case the use of pPhysicalDeviceGroupProperties[0].pNext is undefined and may not work correctly with validation enabled The Vulkan spec states: pNext must be NULL (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkPhysicalDeviceGroupProperties-pNext-pNext)
VUID-VkPhysicalDeviceGroupProperties-sType-sType
Validation Error: [ VUID-VkPhysicalDeviceGroupProperties-sType-sType ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xc9edee8b | vkEnumeratePhysicalDeviceGroups: parameter pPhysicalDeviceGroupProperties[0].sType must be VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkPhysicalDeviceGroupProperties-sType-sType)
VUID-VkPhysicalDeviceGroupProperties-pNext-pNext
Validation Error: [ VUID-VkPhysicalDeviceGroupProperties-pNext-pNext ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf7a24f8d | vkEnumeratePhysicalDeviceGroups: value of pPhysicalDeviceGroupProperties[0].pNext must be NULL. This error is based on the Valid Usage documentation for version 162 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case the use of pPhysicalDeviceGroupProperties[0].pNext is undefined and may not work correctly with validation enabled The Vulkan spec states: pNext must be NULL (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkPhysicalDeviceGroupProperties-pNext-pNext)
Number of device groups: 1
    Device Group: 0 Number of physical devices: 1 Supports subset allocation: false
        Physical available_device: 0 Name: AMD Radeon RX 5700 XT (Discrete GPU)

Hardware accelerated ray tracing is not supported.
Missing features:
    bufferDeviceAddress
    bufferDeviceAddressMultiDevice
VUID-vkGetBufferDeviceAddress-bufferDeviceAddress-03324
Validation Error: [ VUID-vkGetBufferDeviceAddress-bufferDeviceAddress-03324 ] Object 0: handle = 0x77c8ec0000000049, name = NULL BUFFER, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xa641531b | vkGetBufferDeviceAddress: The bufferDeviceAddress feature must: be enabled. The Vulkan spec states: The bufferDeviceAddress or VkPhysicalDeviceBufferDeviceAddressFeaturesEXT::bufferDeviceAddress feature must be enabled (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkGetBufferDeviceAddress-bufferDeviceAddress-03324)
```

**Comment by frank-ourmachinery** [comment] 2021-02-01 06:57
The dump file contains dlls loaded with hot reloading which means I can't debug them.
You don't seem to be running with the hot reload option so I'm guessing that some old dlls are still in the plugins folder.
Those might be causing your issue. 
![image](https://user-images.githubusercontent.com/70658773/106424546-a869a300-6462-11eb-9276-cac4797ab71f.png)

**Comment by khskarl** [comment] 2021-02-01 10:03
Sorry, I didn't notice that before, when I run `the-machinery` it generates `.hot-reload.dll` files for all the dlls that come with TM by default before crashing, and I send a dump from a consecutive run rather than a clean first time run.

The following is a dump for a clean first time run using `--no-hot-reload` and `--safe-mode`, the issue persists. I have also made sure to use a new folder free from old files. (That's enough for a clean install or am I forgetting something?).
[the_machinery_exe 2021-02-01 06.54.59.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/5903203/the_machinery_exe.2021-02-01.06.54.59.dmp.zip)

**Comment by frank-ourmachinery** [comment] 2021-02-01 10:29
The new dump file works perfectly for me. Your steps seem fine to me, I'm probably doing something wrong when the previous dump file you provided. The crash is being caused by the ray tracing addition.

We're using the VK_KHR_acceleration_structure Vulkan extension (among others) for the ray tracing support. That stated that it required VK_KHR_buffer_device_address to be supported. it seems like your GPU doesn't support some features in the latter extension. Which is very weird as it does seem to support the acceleration structure extension, which you can't create without the device address extension.

I'm adding more checks to make sure this doesn't happen anymore, this will be fixed in the hotfix release, sorry for the inconvenience.

**Closed by frank-ourmachinery** 2021-02-01 10:29 UTC

**Comment by khskarl** [comment] 2021-02-01 11:49
Thank you! And it's no problem!
