### ISSUE TITLE
api-ms-win-shcore-scaling-l1-1-1.dll missing

### ISSUE THREAD

**Issue by UnidayStudio** [OurMachinery/themachinery-public#201] opened 2020-04-24 21:33 UTC
When I try to open the-machinery.exe I got an error message saying that the dll:
```
api-ms-win-shcore-scaling-l1-1-1.dll
```
is missing.

Here is a screenshot (in portuguese, but I decided to include here anyways):
http://prntscr.com/s5h9ro

I'm running Windows 7 due to compatibility with proprietary in house apps of my company. I suspect that it's a Win10 specific dll... Am I right? (meaning no Win7 support?)

Thank you.

**Comment by niklas-ourmachinery** [comment] 2020-04-25 03:36
Yes, we do not support Win7 yet. @karl-ourmachinery looked into it a little while ago and while it shouldn’t be too much work, it wasn’t completely trivial either.

**Comment by karl-ourmachinery** [comment] 2020-12-05 21:58
Duplicate of #123

**Closed by karl-ourmachinery** 2020-12-05 21:58 UTC
