### ISSUE TITLE
Crash in thumbnail__validity_hash

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1053] opened 2022-02-16 14:43 UTC
- **Version:** Git Master Branch
- **OS:** Windows

I'm running the-machinery as a collaboration server, and got a crash with the callstack
```
 	the-machinery.exe!is_alive(const tm_the_truth_o * tt, tm_tt_id_t object) Line 1525	C
>	tm_entity.tm_hot_reload.dll!thumbnail__validity_hash(tm_tt_aspect__refresh_thumbnail_o * inst) Line 513	C
 	tm_asset_thumbnails.tm_hot_reload.dll!refresh_thumbnail(tm_asset_thumbnails_o * context, tm_tt_id_t asset, bool asset_dirty, tm_renderer_resource_command_buffer_o * res_buf, tm_renderer_command_buffer_o * cmd_buf, tm_renderer_resource_command_buffer_o * late_res_buf) Line 785	C
 	tm_editor_views.tm_hot_reload.dll!private__browser_draw_icon(tm_ui_o * ui, const tm_ui_style_t * uistyle_in, tm_asset_browser_o * ab, tm_rect_t icon_r, tm_tt_id_t asset, tm_the_truth_o * tt, bool is_cut, const tm_asset_labels_t * all_asset_labels, const unsigned int * asset_label_indices, tm_renderer_resource_command_buffer_o * res_buf, tm_renderer_command_buffer_o * cmd_buf, tm_renderer_resource_command_buffer_o * late_res_buf) Line 3056	C
 	tm_editor_views.tm_hot_reload.dll!private__browser_grid_ui(tm_asset_browser_o * ab, tm_tt_id_t asset_root, tm_ui_o * ui, const tm_ui_style_t * uistyle_in, tm_rect_t browser_r, unsigned __int64 tab_id) Line 4446	C
 	tm_editor_views.tm_hot_reload.dll!asset_browser_ui(tm_asset_browser_o * ab, tm_tt_id_t asset_root, tm_ui_o * ui, const tm_ui_style_t * uistyle_in, tm_rect_t rect, unsigned __int64 tab_id) Line 4685	C
 	the-machinery-dll.tm_hot_reload.dll!tab__ui(tm_tab_o * tab, tm_ui_o * ui, const tm_ui_style_t * uistyle, tm_rect_t content_r) Line 48	C
 	tm_ui.tm_hot_reload.dll!private__draw_ui_task(void * data) Line 2139	C
 	tm_ui.tm_hot_reload.dll!ui(tm_ui_o * ui, const tm_ui_style_t * uistyle, tm_ui_renderer_o * ui_renderer, tm_rect_t rect, bool ui_has_focus, const tm_os_dropped_file_t * dropped_files, unsigned int num_dropped_files, tm_tab_create_context_t * create_context, tm_the_truth_o * settings_tt, tm_tt_id_t settings_obj, float default_padding, tm_docking_workspaces_bar_mode workspaces_bar) Line 2628	C
 	the-machinery-dll.tm_hot_reload.dll!update_editor_gui(tm_application_o * app, tm_ui_renderer_o * ui_renderer, tm_renderer_resource_command_buffer_o * res_buf, window_t * window, bool * close_window) Line 1506	C
 	the-machinery-dll.tm_hot_reload.dll!tick_application(tm_application_o * app) Line 6590	C
 	tm_ui.tm_hot_reload.dll!infinite_progress_box(const char * title, const char * text, float(*)(void *) callback, void * callback_data) Line 356	C
 	the-machinery-dll.tm_hot_reload.dll!save_project_with_type(tm_application_o * app, const char * path, unsigned int type) Line 5250	C
```
Unhandled exception thrown: read access violation.
**tt** was 0x1AC3F800000.

The 3F800000 part seems more like a float than a pointer, so this might be a memory stomp.

I don't have a repro, so this issue is just for visibility

**Comment by karl-zylinski-ourmachinery** [comment] 2022-06-09 16:53
Closing since we've had no more reports on this, and it being too hard to reproduce.

**Closed by karl-zylinski-ourmachinery** 2022-06-09 16:53 UTC
Labels: crash
