### ISSUE TITLE
Corrupted project when saving procedural forest as directory project

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#1119] opened 2022-03-04 09:59 UTC
- **Version:** Git Master Branch
- **OS:** Windows
-----
- Open latest procedural forest (it's on the company dropbox).
- Save as directory project.
- Close and re-open The Machinery.
- Open the saved directory project.
- It fails to load, says buffers are missing.

**Comment by leonardo-ourmachinery** [comment] 2022-03-07 07:51
Encountered this in my personal project too, and I can confirm that if I save the project as an asset database instead of a directory project at step 2, the bug doesn't show up.

**Comment by leonardo-ourmachinery** [comment] 2022-03-07 09:12
It seems that any data migration step that migrates data (I hardcoded one that just returns true as the first statement and does nothing else) will trigger this.

**Comment by leonardo-ourmachinery** [comment] 2022-03-07 10:39
The bug seems related to the fact that when we migrate the project we call `message_box()`.

Another possible hint:

In my project, these are the task spawned if I comment out the `message_box()` call at the end of `load_any_project`:
![image](https://user-images.githubusercontent.com/70660839/157014859-bff1d97a-25d7-42a8-b439-0a019deb630e.png)

While these are the tasks spawned if I don't comment it out (and the project breaks):
<img width="549" alt="image" src="https://user-images.githubusercontent.com/70660839/157015278-28e8b958-ab23-4029-86a0-e81c9ed4e75f.png">

I've also noticed that in the "breaking" case the number of task spawned is not always the same: I got 160 tasks this time but 159 the previous one (I also saw 161 and 158 I think).

**Comment by leonardo-ourmachinery** [comment] 2022-03-07 12:51
Offending commit: https://github.com/OurMachinery/themachinery/commit/9c2e0f79804b0bb26ffa784d2fdcceae6aa93c2f 
(Buffer compression)

**Comment by niklas-ourmachinery** [comment] 2022-03-07 16:51
I will investigate it.

**Comment by leonardo-ourmachinery** [comment] 2022-03-07 17:19
The problem seems to be related to the fact that the modal is shown while there may be other buffers being saved here (`the_truth_assets.c`):

```
            struct save_buffer_task_t *ud = tm_alloc(std->allocator, sizeof(*ud));
            *ud = (struct save_buffer_task_t){
                .allocator = std->allocator,
                .buffer_path = buffer_path,
                .buffer_len = buffer_len,
                .buffer_data = buffer_data,
            };

            struct tm_task_system_api *tm_task_system_api = tm_get_api(tm_global_api_registry, tm_task_system_api);
            tm_carray_push(std->tasks, tm_task_system_api->run_task(private__save_buffer, ud, "compress_and_save_buffer", 0, false), std->allocator);
```

If I save the buffers immediately the bug goes away.

**Comment by leonardo-ourmachinery** [comment] 2022-03-08 08:40
Fixed in master via https://github.com/OurMachinery/themachinery/commit/e51dcffdf639c18ea2f3038ecf0f1d1a54ff7a34

@karl-zylinski-ourmachinery I verified that the problem went away in my project, can you double check that it's gone in the forest sample too?

**Closed by leonardo-ourmachinery** 2022-03-08 08:40 UTC
Labels: bug
