### ISSUE TITLE
Asset property undo does not work

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#215] opened 2020-05-03 17:50 UTC
Steps to reproduce:
- Create New Physics Material
- Change Restitution from 0.1 to 0
- Undo (Ctrl-Z)

Notice how the New Physics Material is removed instead of the Restitution property reverting to 0.1.

Btw, is Asset the correct terminology here? ie when refering to an object in the asset browser as opposed to an component "object" (for which Undo works as expected).

**Comment by niklas-ourmachinery** [comment] 2020-05-05 22:41
Reproduced. Asset is the right terminology.

This one is a bit trickier than it might seem. We keep track of separate undo stacks per "document"/"asset". The problem here is that the Property window is editing things that belong to different undo stacks.

![image](https://user-images.githubusercontent.com/26548514/81122391-a5e31880-8ee5-11ea-86da-a591bcac258d.png)

*Static Friction*, *Dynamic Friction* and *Restitution* are part of the asset, so any edits go into the *asset's* undo stack.

However the *File Name* belongs to the file tree undo stack which keeps track of file tree changes (moves, renames, etc) that typically can't be associated with any single asset. (The file tree stack also keeps track of multi-edit operations across assets.)

In this case, the *Undo* menu is connected to the file tree stack, so only changes made to the file tree stack will show up there. That means that you can't get to the changes made to the asset stack.

I'm not 100 % sure what the best approach to fix this is. The whole setup with separate asset undo stacks is a bit confusing when it comes to things like file tree operations and multi-editing assets. However, people seem to prefer it to using a single global undo stack, since it allows you to undo changes to individual assets separately.

One approach might be to give each  **Tab** it's own undo stack. That might be less confusing in some cases, but more confusing in others (i.e. changes made in the Entity Tree tab can't be undone in the Scene tab, and if you close a tab you lose the ability to undo the changes that were made in that tab).

Will have to mull over this a bit to see if I can either find a better solution for Undo in general or a quick fix for this particular issue without changing how Undo works in general.

**Comment by niklas-ourmachinery** [comment] 2020-05-05 23:07
Ok, after pondering this a bit, I did a temporary quick fix for this that in this specific case of a selected asset associates the **Properties** window with the *asset's* undo stack rather than the *file tree* undo stack. This means you can now Undo the Restitution from the Properties window, however if you change the File Name and want to undo it, you have to to that from the Asset Browser tab.

I think that's a decent workaround for now and will think a bit more if we need to make any more changes to the undo strategy.

(Another option would be to let the same undo event appear in multiple undo stacks. For example, we could put File Name changes into *both* the *asset* stack and the *file tree* stack, so that they could be undone either from the Properties window or the Asset Browser. We could put multi-edit operations into the undo stack for *all* the edited assets, allowing them to be undone from any one asset. I think this is how some editors implement undo for global Search & Replace.)

**Closed by niklas-ourmachinery** 2020-05-05 23:07 UTC
Labels: design-decision

**Comment by peterlindgren** [comment] 2020-05-06 10:55
Thanks for the detailed description.

I'll add that from my user perspective, I was expecting the property editor to undo because I had changed the focus and my last inputs were in it. If I had undone everything in the property editor stack (that I had input after switching focus) I think I would've also expected it to jump to the file tree's undo stack,. So in my mind I was expecting a global undo for that scenario.

**Comment by niklas-ourmachinery** [comment] 2020-05-06 13:19
We used to have a global undo stack... it kind of makes more sense to me too... and it's also a lot simpler to implement. 😄 But in talking to people I've found out that some people rely very heavily on having per-document undo stacks -- i.e. they will do a bunch of changes in document-1, then do bunch of changes in document-2, then go back to document-1 and want to undo the changes they did there without disturbing document-2.

Although I'm not a big fan of configuration options in general, maybe this is a case where we should offer both options.

**Comment by peterlindgren** [comment] 2020-05-06 16:45
I think the main source of confusion in this case is that it's unclear what a document is and when I'm switching between them. I probably associate the asset as the document but in the editor the file tree is one document (or a view of the asset) and the property editor is another.

Perhaps some part of the UI could indicate what document (ie undo stack) you're on? Or a more much more "global undo" approach would be to share the undo stack for an entire window.
