### ISSUE TITLE
Overridden transform values on prototype entity does not save

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1110] opened 2022-03-03 14:22 UTC
Latest Binary Release
Windows

Doing an override on transform of entity prototype in another entity (scene) and pasting/writing in new values does not save.
Shutting down editor and re-opening I get the same values as before, and transform is not overridden anymore.

I am working on collaboration server.

**Comment by karl-zylinski-ourmachinery** [comment] 2022-03-04 15:39
Could not reproduce.
Here's what I did:
- Right click in asset browser -> New -> Entity
- Drag that entity into world.entity (into scene tab)
- Make sure to remove override of transform component in the entity I just dragged in (transform component is instantiated by default when you drag the entity in).
- Connect a client to this project in collaboration
- Override the transform
- Key in values
- Save on client
- Disconnect on client
- Close and reopen project
- Transform is still overridden and values are there

**Comment by niklas-ourmachinery** [comment] 2022-03-04 20:32
I couldn't reproduce either.

**Comment by TobiasElemental** [comment] 2022-03-05 07:46
My steps: 

- drag a prototype entity into another entity 
- override transform component in prototype
- ctrl+c on another transforms values 
- ctrl+v on overidden transform values 

Did not key in values one by one but whole transform values with paste.

**Comment by Tisten** [comment] 2022-03-05 15:29
I got the bug in latest master when trying now, this is what I did:
* Started `the-machinery.exe --host-lan-server", it opened with an empty default project.
* Started `the-machinery.exe", opened the collaboration tab and connected to the LAN server.
* In this collaboration client, I selected "post_processing_stack" in the Entity Tree tab
* In the Properties tab I right clicked the transform component and chose "Override Tree"
* I changed the position to 1, 0, 0
* Now I right-clicked the "Transform Component" header in the Properties tab (where the collapsable icon is) and chose "Copy"
* I now expanded the "sky" entity in the Entity Tree tab, in both editors
* In the client editor I right clicked the "Transform" component of the "sky" entity in the Entity Tree, and chose "Paste Values"
Here is the client, before and after the "Paste Values":
![image](https://user-images.githubusercontent.com/6726075/156889120-f31b4ae1-44cf-4e46-935b-222ddfdc1264.png)
And here is what happened on the server, before and after "Paste Values":
![image](https://user-images.githubusercontent.com/6726075/156889759-4d30c4a9-0b8c-42ea-aad8-afb1b4628e63.png)

Before the "Paste Values" the transform of "sky" was marked as overriden (by the way, why is the default sky overriden on x and z?) and the result was that the client got the new values, but the server lost the "overriden" state and didn't get any values.

**Comment by Tisten** [comment] 2022-03-05 16:33
Don't know it it gives any more clues, but an undo and redo of this change gave these errors:
```
❌ c:\Dev\themachinery\foundation\the_truth.c(2462): error: Object `107600000412` of type `tm_position` already has an owner `1075000004b9 -> 14cf000000b9`
❌ c:\Dev\themachinery\foundation\the_truth.c(2462): error: Object `107800000413` of type `tm_rotation` already has an owner `1075000004b9 -> 14cf000000b9`
❌ c:\Dev\themachinery\foundation\the_truth.c(2462): error: Object `107900000414` of type `tm_scale` already has an owner `1075000004b9 -> 14cf000000b9`
```

**Comment by leonardo-ourmachinery** [comment] 2022-03-08 14:35
Fixed in master.

I'm still investigating why there are a bunch of errors when undoing/redoing (even though the operation is done correctly)... but that's another story.

**Closed by leonardo-ourmachinery** 2022-03-08 14:35 UTC
Labels: hard-to-reproduce, more-information-needed
