### ISSUE TITLE
Meshes disappear when re-parenting them

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#1017] opened 2022-02-12 20:59 UTC
- **Version:** Git Master Branch 
- **OS:** Windows  

1) I have a scene with a mesh entity inside of it
2) Create an empty entity
3) Re-parent the mesh entity "under" the new empty entity
4) Notice the mesh is no longer rendered
5) Open another scene in the scene preview
6) Return to the previous scene, notice that the mesh is now rendered correctly

I also see messages similar to these appearing in the console, I am unsure if they are related, but I have included them here for completeness.
```
❌ C:\gamedev\themachinery\plugins\ui\ui.c(2009): error: ui: Active data for ID 20000048 has wrong format f0b9e627200be571, expected 4c9b61dcc710e971.
❌ C:\gamedev\themachinery\plugins\ui\ui.c(2009): error: ui: Active data for ID 18000132 has wrong format 48f8d0d5e8348e67, expected 4c9b61dcc710e971. (2)
```

**Comment by Tisten** [comment] 2022-02-13 19:30
This bug is widespread in the master branch. It can also be reproduced by opening a new project, and dragging any of the core geometry (box, sphere or plane) into the world entity. Neither of them will become visible. If you now switch entity and then go back again they will all be there.

You can also "duplicate" any of the shapes, and the duplicated entity will be invisible. It can be made visible by multiselecting the invisible shape together with any other shape in the entity view.

I don't get any log message while doing this.

**Comment by tobias-ourmachinery** [comment] 2022-02-14 08:40
Regression introduced by mistake last Friday, fixed in master branch now.

Note: I couldn't reproduce the `Active data for ID` errors in the console following the above steps. Those are unrelated to meshes being invisible. If you have a repro for those, please open another issue. Thanks!

**Closed by tobias-ourmachinery** 2022-02-14 08:40 UTC
