### ISSUE TITLE
Editor memory usage increasing for a long run

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#645] opened 2021-07-20 06:52 UTC
Memory usage is increasing when you run editor.

How to reproduce:

1. Download [test project](https://github.com/infosia/themachinery-issues/blob/master/0013/project.the_machinery_db), open it in the editor
2. Start simulating
3. Wait for 10 minutes

Memory usage (reported from "Memory Use")

1. Right after starting simulator = 474MB
![Capture2](https://user-images.githubusercontent.com/1661068/126274296-2ffa32cb-3fd9-4f75-87f5-bbdce28b67e2.PNG)

2. 10 minutes later = 3.2GB
![Capture3](https://user-images.githubusercontent.com/1661068/126274734-45785a43-0530-44d6-ae7b-bcc313c50734.PNG)

For me this does not happen on the `runner`.

**Comment by simon-ourmachinery** [comment] 2021-07-20 07:03
Can ou give me some information I am missing:

Is this the -dev version aka "source code" access version or the binary version?

**Comment by infosia** [comment] 2021-07-20 07:21
I assumed original reporter (Micha) is using binary version. I'm using latest "source code" version and run it on the Visual Studio.

**Comment by tobias-ourmachinery** [comment] 2021-07-20 08:07
Tested this in latest version of master (I'm on commit `0e50a5ba2b55bc1d8365744433a8b367717e11aa`) right now and I can't reproduce it. Running from your project, with Simulate tab in focus. For me the creation_graph_interpreter.c:535 is stable at 147MB even after fifteen minutes. Maybe my fix for `tm_hash_remove()` yesterday also fixed this. Can you try it again on your side running with the latest code in master?

Thanks!

**Comment by Micha0** [comment] 2021-07-20 08:51
Actually, I was running the git version through Visual Studio aswell. Will try the latest master.

**Comment by infosia** [comment] 2021-07-20 09:15
I'm on latest master `0e50a5ba2b55bc1d8365744433a8b367717e11aa` and running it on Debug mode through Visual Studio.

![Capture](https://user-images.githubusercontent.com/1661068/126293303-7234d007-7f80-4176-ae69-265da98c7c75.PNG)

I also tried on the editor `2021.6.b` binary and saw gradual memory increase on the editor too. (It takes much lower memory than Debug mode through VS and takes longer time to see memory spike but it's definitely increasing).

**Comment by tobias-ourmachinery** [comment] 2021-07-20 09:23
In the initial screenshots attached with this issue you had screenshots from the Memory Tab where you clearly could see that `creation_graph_interpreter.c:535` was one big offenders. Are you still seeing this in latest master? I'm not.

As for `2021.6.b` we already know that there's a leak in a hash map used in the memory tracker, so no point in test on that. That leak has been fixed in master.

**Comment by simon-ourmachinery** [comment] 2021-07-20 09:28
https://github.com/OurMachinery/themachinery/commit/860d9189c3971a09c99e0811dd3326119101850e

**Comment by infosia** [comment] 2021-07-20 09:36
Yes, `creation_graph_interpreter.c:535` is still the issue.

(Capture from the editor running 5 minutes through VS Debug mode)
![Capture2](https://user-images.githubusercontent.com/1661068/126299170-27e8de52-2349-49c3-b22c-a413ac0be13a.PNG)

**Comment by tobias-ourmachinery** [comment] 2021-07-20 10:47
We must be doing something slightly different, I tried to follow your repro steps exactly but on my end memory usage is stable at 89MB for `creation_graph_interpreter.c:535` after 20 min with the simulate tab in focus. Hmm..

**Comment by tobias-ourmachinery** [comment] 2021-07-20 11:20
Finally reproduced. It's something funky with the thumbnail refresh. We'll dig into it. Thanks!

**Comment by tobias-ourmachinery** [comment] 2021-07-20 13:11
So there are two problems:

1. Memory management for creation graph instances was flawed in a way that recycled instances would not be able to recycle memory for wires and variables. Since memory backing for wires and variables relies on requesting memory from a block allocator owned by the interpreter it won't be freed until the interpreter gets destroyed. I'm working on rewriting the memory management for creation graphs here: https://github.com/OurMachinery/themachinery/tree/better-memory-management-for-creation-graphs

2. Right now only creation graphs producing images can generate thumbnails, for other creation graphs (like materials) the thumbnail service will try to generate thumbnails (by instancing the creation graph, request its output and destroy the instance) but fail. Each frame all creation graphs not supporting thumbnail generation are currently getting instanced / ran and destroyed. This is obviously not what we want and will be fixed before the thumbnail generation is has its feature flag removed.

**Comment by tobias-ourmachinery** [comment] 2021-07-21 14:48
Fixed.

**Closed by tobias-ourmachinery** 2021-07-21 14:48 UTC

**Comment by infosia** [comment] 2021-07-22 02:13
Confirmed it's fixed for me too. Awesome! 👍
