### ISSUE TITLE
Non-fatal: NULL object while loading a project

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1335] opened 2022-05-24 08:21 UTC
- **Version:** Git Master Branch
- **OS:** Windows

I connected to a collaboration server, and before the project was fully loaded I got this:

![image](https://user-images.githubusercontent.com/6726075/169983310-953ee44d-429c-475a-9f74-3428df788938.png)

I.e the asset browser's asset root had been updated, but the asset root object was not yet accessible.

After getting 5 asserts about fallout from this, the project successfully loaded and the editor was fine, so the problem is not fatal.

I've connected to the collaboration server a thousand times before this without seeing this error, and the next time I tried it was fine again so this error is rare and hard to reproduce.

**Comment by simon-ourmachinery** [comment] 2022-07-01 11:26
I am closing this issue since we were not able to reproduce it. If this happens again we will open it again.

**Closed by simon-ourmachinery** 2022-07-01 11:26 UTC
Labels: hard-to-reproduce
