### ISSUE TITLE
Opening the same project twice locks up the editor.

### ISSUE THREAD

**Issue by Hoogin** [OurMachinery/themachinery-public#584] opened 2021-06-17 10:05 UTC
- Open the same project twice in a row
- Editor locks up and window turns black
- Editor does not seem to recover from this state
- Doesn't matter which project I try to open twice

I'm running Linux, Slackware 15 Beta.

**Comment by leonardo-ourmachinery** [comment] 2021-06-17 15:02
@Hoogin thank you very much for reporting the issue.
Can I ask you if the problem is reproducible with both "db" and "directory" projects?

@raphael-ourmachinery I'm not able to repro this on Windows.
Can you try to see if you're able to repro it on Linux?

**Comment by raphael-ourmachinery** [comment] 2021-06-17 15:58
@Hoogin thank you for the report, I cannot reproduce it on my Linux setup, but will install Slackware and try to reproduce it.

**Comment by Hoogin** [comment] 2021-06-17 23:13
- I created a new project and saved it as a directory project
- Reopened the same project and no lock up
- Saved it as a db project
- Opened the db project again, Locked up

In the console I don't get any output when it locks up.

If you install Slackware, since the 14.2 release is now several years old, you have to upgrade to Slackware current to get the Slackware 15 beta. 15 seems pretty close to release however but with Slackware it's done when it's done. Compile and install the xcb-util-xrm package from slackbuilds.org. Everything else should be included in 15, except for proprietary GPU drivers of course. Slackware isn't exactly mainstream though.

**Comment by raphael-ourmachinery** [comment] 2021-06-18 17:35
@Hoogin I was able to reproduce by following these steps, thank you for the detailed report, we'll work on fix that.

**Comment by raphael-ourmachinery** [comment] 2021-06-18 19:26
@Hoogin it will be fixed on the next release. Thanks again!!

**Closed by raphael-ourmachinery** 2021-06-18 19:26 UTC
Labels: hard-to-reproduce
