### ISSUE TITLE
Property window doesn't update after starting up editor

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#457] opened 2021-01-16 08:27 UTC
Twice now, I've started TM and the prop window hasnt' updated when I clicked an asset, simply stating "Select something".

Only after I clicked on the property window would it then register asset selections.

**Comment by karl-ourmachinery** [comment] 2021-01-16 21:12
Did you perhaps have two property windows open? One "hidden" (i.e. something else is selected in the tab well) and another that is visible? I've seen a similar bug where the hidden one got the properties until I closed it.

**Comment by Srekel** [comment] 2021-01-17 10:18
It's quite possible that the properties window was pinned when I closed the editor down. 

The first time I'm pretty sure I only had one window open, the second time, it's possible I had two.

**Comment by simon-ourmachinery** [comment] 2021-03-29 16:32
closed because cannot reproduce

**Closed by simon-ourmachinery** 2021-03-29 16:32 UTC
