### ISSUE TITLE
Properties tab doesn't show inherited component properties (individually)

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1020] opened 2022-02-14 07:32 UTC
- **Version:** Git Master Branch
- **OS:** Windows

As a user I would like to see the properties of the selected component. Currently the only way to see the properties of an inherited component is to select the entity node itself.

**Comment by niklas-ourmachinery** [comment] 2022-02-15 20:34
We're working on better workflows for inherited objects in general. Unfortunately it's not a quick fix, since it requires some replumbing, but stay tuned.

**Comment by karl-zylinski-ourmachinery** [comment] 2022-06-13 12:06
Duplicate of https://github.com/OurMachinery/themachinery-public/issues/447

**Closed by karl-zylinski-ourmachinery** 2022-06-13 12:06 UTC
