### ISSUE TITLE
[UX] Entity dropdown menu in Scene tab should be disabled when entity is assigned?

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#654] opened 2021-07-23 16:56 UTC
https://user-images.githubusercontent.com/27040/126812341-88789e60-7b92-4428-a376-471764087142.mp4

The behavior of the entity dropdown menu is confusing.  If I have a Scene with an entity assigned to it, opened via double click. Using the menu doesn't seem to do anything unless I select the same entity that was assigned.  In the video, I have "world" assigned to the Scene, then select it in the dropdown.  When I change the camera, there are duplicates.  Selecting the wrong one can lead to a crash when lighting is manipulated.

I think it makes sense to disable the entity dropdown menu when an entity has been assigned to the Scene tab.

**Comment by karl-zylinski-ourmachinery** [comment] 2021-11-25 20:51
I'll look into the crash, but the major UX problem here is that it's unclear what the picker is for. It is just the picker for choosing a lighting environment. And the push button to the left of the picker enables that lighting environment. It is enabled automatically when the scene tab opens an entity that has no lights (with the default_lighting_environment set as lighting environment entity) .
![image](https://user-images.githubusercontent.com/57644882/143498533-348de48e-23d2-4f26-a0eb-b904e1e8d12a.png)

I'll try to improve the UI.

**Comment by niklas-ourmachinery** [comment] 2021-11-30 17:31
I agree... I find this dropdown really confusing... the most confusing thing to me is that ALL entities appear in there... not just entities that are "lighting environments"... which kind of makes sense, because there is nothing special about a "lighting environment" entity... but it gets really confusing.

@geekrelief The extra cameras appear in the camera menu, because the lighting environment gets spawned into the scene and if that lighting environment has cameras, those cameras will be shown in the camera menu.

I tried reproducing the crash by selecting the cameras from the lighting environment, but I wasn't able too. Do you have explicit steps for reproducing the crash?

**Comment by karl-zylinski-ourmachinery** [comment] 2021-11-30 20:10
I'll try to add some sort of categorization for lighting environments. Made a tag.

**Comment by geekrelief** [comment] 2021-12-02 18:01
@niklas-ourmachinery With regards to the camera crash, it looks like the problem is fixed.

**Comment by karl-zylinski-ourmachinery** [comment] 2022-06-09 14:09
Fixed in https://github.com/OurMachinery/themachinery/commit/95f356f1fc80d5670e36072ee23a598d54182e56

Picker now only shows lighting environment assets tagged with the new 'lighting environment' asset label. See the commit message for more details.

**Closed by karl-zylinski-ourmachinery** 2022-06-09 14:09 UTC
Labels: ux
