### ISSUE TITLE
"Unexpected nil item" during collaboration using Mannequin sample

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#72] opened 2020-01-21 11:00 UTC
Repro: Open Mannequin sample and host collaboration. Join with another client. Both server and client get lots of these errors:
![assert](https://user-images.githubusercontent.com/57644882/72799409-76b1df80-3c45-11ea-93ce-e7817dea5cbe.png)

It seems to be due to creation graph interface lacking an owner.

**Comment by niklas-ourmachinery** [comment] 2020-01-23 22:46
This in creation_graph.c:1734 returns 0:

~~~c
uint64_t creation_graph = tm_the_truth_api->owner(manager->tt, graph_interface);
~~~

Since this only happens in collaboration mode, the objects that create problem must be coming in from the client. 

If I sent a breakpoint in `recv_changelong()` I can see that the host indeed gets a chunk of 11.5 K of data that contains 68 objects of type `tm_creation_graph_interface`.

**Comment by niklas-ourmachinery** [comment] 2020-01-27 23:46
This can also be reproduced in a completely empty collaboration session:

1. Start two executables for client and host
2. Start hosting a collaboration session
3. Join with the client

At this point, a number of `Unexpected nil item` error messages are printed on the host

**Comment by niklas-ourmachinery** [comment] 2020-01-27 23:49
It might be that in this case the objects are not permanently without owners, they are just *temporarily* without owners. Because, as soon as an object is committed it can be transferred over the collaboration connection to the other side. Thus, there is a possibility that the collaboration side "sees" the object before it has been set as the subobject of another object.

**Comment by niklas-ourmachinery** [comment] 2020-01-27 23:52
This seems to fix it:

https://github.com/OurMachinery/themachinery/commit/db075ed117348b0b41827145fcc715211d9e4969

@tobias-ourmachinery can you verify that this is a reasonable fix?

**Closed by niklas-ourmachinery** 2020-01-27 23:52 UTC
Labels: bug
