### ISSUE TITLE
Collaboration: Lazy buffer loading

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#1099] opened 2022-02-28 12:59 UTC
- **Version:** Git Master Branch 
- **OS:** Windows

When initiating a collaboration session, the whole project is sent over. We tried to do this with the procedural forest demo and ran into giant initial buffer send times. Instead, the buffers should be sent one by one, lazily. This means that the streamable buffers API can have some sort of hook to ask the collaboration API for buffers when they are missing.

This would also help building the collaboration buffer cache (the local client buffer cache). We had some crashes when we tried to send our initial giant buffers blob, and then those buffers never got cached on the client, so we had to do the big transfer again and again. Lazily loading them one by one would ensure that the local cache is filled buffer-by-buffer.

**Comment by niklas-ourmachinery** [comment] 2022-02-28 16:42
Agreed... this has been my plan for some time.

The best solution would be if the client doesn't have to stall while waiting for a buffer to download, but instead just signal that it wants the buffer, continue to run with a zero buffer and then slot in the "actual" buffer when it arrives.

But that would require all code that uses buffers to be able to deal with "zero buffers" and also be able to slot in the "actual" buffer later.

If we stall while waiting for buffers we can avoid that... but that can cause other problems... we have to "pump" the network layer while stalled which leads to weird control flows. Also, the stall could potentially last for minutes for big buffer, making the UI completely unresponsive for long times. Because of this, I don't think "stalling" works even as a temporary fix, we have to go for the full solution.

**Comment by Tisten** [comment] 2022-02-28 17:18
This is a duplicate of https://github.com/OurMachinery/themachinery-public/issues/965

**Comment by niklas-ourmachinery** [comment] 2022-02-28 17:21
Closing as duplicate.

**Closed by niklas-ourmachinery** 2022-02-28 17:21 UTC
Labels: enhancement
