### ISSUE TITLE
Machinery crashes when interpreting this graph

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1090] opened 2022-02-24 18:08 UTC
- **Version:** Git Master Branch
- **OS:** Windows

Attached a project which crashes when a simulation tab is opened for the world entity.
[CrashingGraph.zip](https://github.com/OurMachinery/themachinery-public/files/8134762/CrashingGraph.zip)

To work around this crash I added checks in graph_nodex.c so entity_ctx isn't null, but I would like to understand why the entity is 0, and why the entity_ctx is null instead.

**Comment by karl-zylinski-ourmachinery** [comment] 2022-02-24 19:58
I have looked at bit at this, and I'm pretty sure this is what is going wrong:

When it crashes I see `trigger_remote_event_node_f` in the callstack. This node fetches some other graph component on another entity and triggers an event on it. This happens during `asset_loaded` of the entity that called `trigger_remote_event_node_f` node. In `asset_loaded` we see that `private__reset_asset(man, e, c);` is run, which does this:

```
tm_entity_context_o **ctx = tm_graph_interpreter_api->write_wire(c->gr, TM_GRAPH_COMPONENT__STATIC_WIRE__ENTITY_CONTEXT, 1, sizeof(*ctx));
*ctx = man->ctx;
tm_entity_t *ep = tm_graph_interpreter_api->write_wire(c->gr, TM_GRAPH_COMPONENT__STATIC_WIRE__ENTITY, 1, sizeof(*ep));
*ep = e;
```

The graph (component) that `trigger_remote_event_node_f` calls probably hasn't done this yet. I guess one could write the entity ctx and entity on those wires when `trigger_remote_event_node_f` runs, but I'm thinking that there probably is a depedency-problem here where this graph depends on some other graph but that graph hasn't had time to have its `asset_loaded` run yet, i.e. it isn't ready. @niklas-ourmachinery I wonder if we need some sort of dependency system here?

**Comment by Tisten** [comment] 2022-02-25 08:00
Thanks, calling reset_asset in trigger_remote_event_node_f works fine. So my new temp fix is to add this
```
    if (*(tm_entity_context_o **)tm_graph_interpreter_api->read_wire(gc->gr, TM_GRAPH_COMPONENT__STATIC_WIRE__ENTITY_CONTEXT).data == 0) {

        const struct tm_component_i * gci = tm_entity_api->component(entity_ctx, tm_entity_api->lookup_component_type(entity_ctx, TM_TT_TYPE_HASH__GRAPH_COMPONENT));
        gci->gamestate_representation->loaded(gci->manager, entity, gc);
    }
```
here:
https://github.com/OurMachinery/themachinery/blob/8bc8ab5d77754493e082d1526429a48bebe04834/plugins/graph_interpreter/graph_nodes_events.c#L75

Now the graph doesn't crash

**Comment by leonardo-ourmachinery** [comment] 2022-02-28 07:43
I looked into this a bit too, as Karl said the problem is that the children graph's `asset_loaded()` hasn't been called yet when the parent invokes the remote event so the entity_context wire is NULL, thus the crash.

My opinion is that `private__reset_asset()` should get called in the `load_asset()` callback and not in the `asset_loaded()` one. Both the `entity_context` and the `tm_entity_t` are informations we have when `load_asset()` is called, so I personally don't see any reason to delay the assignment to the `asset_loaded()` function.

**Comment by niklas-ourmachinery** [comment] 2022-03-01 22:47
Sorry, accidentally closed this with a commit that was supposed to refer to a different issue.

**Comment by niklas-ourmachinery** [comment] 2022-03-01 23:25
I agree that the right fix is to separate this into multiple phases. One phase were `private__reset_asset()` gets called and a separate one that calls `trigger_event()`.

AFAICT, it should be safe to call `private__reset_asset()` from `load_asset()` so we don't need to introduce an additional "phase".

I implemented this in master and couldn't see any ill effects from it. Let me know if you run into any problems.

**Closed** 2022-03-01 23:25 UTC
