### ISSUE TITLE
Small UI issue in Asset browser

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1001] opened 2022-02-04 20:33 UTC
- **Version:** Git Master Branch
- **OS:** Windows

In grid mode names clip into other names
![image](https://user-images.githubusercontent.com/21057342/152599079-adccc6d8-3604-4ae3-970f-67dd262c65de.png)

**Comment by simon-ourmachinery** [comment] 2022-02-17 15:23
I close this issue since I cannot reproduce it. 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/70658708/154513058-c0189a04-8bc7-4787-93c8-ad3b9cd36f4c.png">

**Closed by simon-ourmachinery** 2022-02-17 15:23 UTC
Labels: bug
