### ISSUE TITLE
Issue with Extract All Assets

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#578] opened 2021-06-08 21:36 UTC
I made the "Extract Assets" button for `.dcc_asset` work with multiselection, so you can click "Extract All Assets" and make entities out of all the assets. "Extract All Assets" basically creates a separate extraction task for each asset.

However, something fishy happens if you do this. If you select a large number of DCC Assets and do this (for example all the assets in `struct/floors` in the `modular-dungeon-kit`) sometimes, some of the assets won't get any meshes:

![image](https://user-images.githubusercontent.com/26548514/121260651-73cd8400-c866-11eb-9e4c-9a737b94b1e9.png)

However if you do this with a single DCC Asset at a time, it works:

![image](https://user-images.githubusercontent.com/26548514/121260730-91025280-c866-11eb-8140-e59b43f07f50.png)

It seems like this test in the entity rigger fails:

~~~c
if (!creation_graph.u64)
    continue;
~~~

But I'm not exactly sure why.

**Comment by karl-zylinski-ourmachinery** [comment] 2021-09-28 13:48
@niklas-ourmachinery Can't reproduce this anymore. Can you try again and close this if you don't see it anymore?

**Comment by karl-zylinski-ourmachinery** [comment] 2021-09-28 14:15
I was able to reproduce it in the end, I'll investigate.

**Comment by karl-zylinski-ourmachinery** [comment] 2021-11-25 20:46
I have fixed another multi DCC asset extraction issue which also seems to have solved this.

**Closed by karl-zylinski-ourmachinery** 2021-11-25 20:46 UTC
