### ISSUE TITLE
Undo while text input field has focus

### ISSUE THREAD

**Issue by theb1rd** [OurMachinery/themachinery-public#409] opened 2020-12-09 06:24 UTC
In beta-2020.11.a, invoking undo while a text input field has focus (e.g. Link.Position.X) reverts both the in-progress text input and the action that preceded text entry.

1) Select a light and change its color
2) Alter the value of Position.X via text input
3) While text input field still has keyboard focus, undo
4) Observe that both color and input text have reverted, but altered state of position has been committed

**Comment by simon-ourmachinery** [comment] 2020-12-10 09:53
Thanks for reporting @theb1rd.
I can confirm the first 3 1/2 steps but I seem to be not able to reproduce the ` but altered state of position has been committed` statement. In my case the colour and the position change but the changed position (in my case 0) did snap back to its initial value. So the alerted state has not been submitted on my end.

**Comment by niklas-ourmachinery** [comment] 2020-12-15 17:58
Fixed for 2020.12

**Closed by niklas-ourmachinery** 2020-12-15 17:58 UTC
