### ISSUE TITLE
Multiple copies when duplicating with the shift drag in scene view

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#952] opened 2022-01-05 11:26 UTC
There is a lot of unwanted duplications of entities when shift click dragging them in the scene view. It seams to happen mostly on entities made up of sub entities. But you need to multiselect entities for it to happen. I have had up to 5 entities stacked on the exact same coordinate after one shift drag.

**Comment by niklas-ourmachinery** [comment] 2022-01-19 23:35
Referenced in #951

**Comment by leonardo-ourmachinery** [comment] 2022-03-30 08:08
@LoffanElemental here the issue is what @niklas-ourmachinery discussed in #951 right?
Meaning if you have a parent and one of his children both selected, you only want the parent to be duplicated. (Which makes sense to me)

**Comment by LoffanElemental** [comment] 2022-03-30 13:16
I have not encountered this issue in the latest versions of TM

**Comment by leonardo-ourmachinery** [comment] 2022-03-30 13:35
That's nice to hear. I'll leave the issue open anyway so that we can keep track of the child/parent duplication problem.

**Comment by leonardo-ourmachinery** [comment] 2022-04-29 12:01
Fixed in master: now both the Entity Tree Tab and the Scene Tab will only duplicate entities that _don't_ have a parent in the current selection.

**Closed by leonardo-ourmachinery** 2022-04-29 12:01 UTC
