### ISSUE TITLE
Editor freezes whenever a file dialog would show

### ISSUE THREAD

**Issue by khornel** [OurMachinery/themachinery-public#613] opened 2021-07-10 21:19 UTC
Tried in version 2021.6.a.

Clicking anything in the UI that would launch the file dialog (Open project, Save project, Import file, downloading sample projects, etc.) freezes the editor.

Dragging assets directly to the asset browser works fine and obviously launching with the default project loaded. There have otherwise been no other issues with the editor.

Specs:
Windows 10 Pro 19043.1083
Intel i7-7820X
32GB RAM
Nvidia Geforce 3090, driver version 465.89
I've tried running the engine from both a Samsung 850 PRO SSD and 960 PRO M.2 SSD

**Comment by niklas-ourmachinery** [comment] 2021-07-10 22:29
Thanks for the report... I'm not sure what could cause this to happen... we might have to send you a special build to try to figure out what is going on.

As a workaround, you can use `the-machinery.exe PROJECT-PATH` from the command-line to open a specific project without showing the windows file dialog boxes.

**Comment by tobias-ourmachinery** [comment] 2021-07-11 09:22
@khornel does the dialog show before the it freezes? If not, can you verify that it’s not hidden behind the editor window. I remember someone had an issue with IO dialogs poping up behind the main window some time ago.

**Comment by khornel** [comment] 2021-07-11 10:05
It freezes before the dialog shows. There doesn't seem to be any other windows, I can't alt-tab or win-tab to anything and moving the editor window to the side before clicking Open project doesn't reveal any dialogs.

The actual File dropdown panel stays frozen on screen after clicking Open project.

**Comment by khornel** [comment] 2021-07-13 09:35
I wrote a quick C program that calls GetOpenFileName, and it ran without any issues. Could you perhaps post how you're calling it or the flags you've set? Maybe I can recreate it.

**Comment by tobias-ourmachinery** [comment] 2021-07-14 12:05
@khornel Here's the initialization code for `OPENFILENAME` passed to `GetOpenFileName()`:

```
    enum { RESERVED_WCHARS = 1024 * MAX_PATH };
    enum { RESERVED_BYTES = RESERVED_WCHARS * sizeof(wchar_t) };

    wchar_t *file = (wchar_t *)virtual_memory_map(RESERVED_BYTES);

    OPENFILENAME of = { 0 };
    of.hwndOwner = GetActiveWindow();
    of.lStructSize = sizeof(OPENFILENAME),
    of.nMaxFile = RESERVED_WCHARS;
    of.lpstrFile = file;
    of.Flags = OFN_EXPLORER + (open->allow_multi_select ? OFN_ALLOWMULTISELECT : 0);
    if (open->extensions) {
        char filter[8 * 1024] = { 0 };
        uint32_t filter_n = 0;
        filter_n += (uint32_t)tm_sprintf(filter + filter_n, "%s", open->description ? open->description : TM_LOCALIZE("Files"));
        filter[filter_n++] = 0;
        for (const char *f = open->extensions; *f;) {
            const char *sp = strchr(f, ' ');
            filter[filter_n++] = '*';
            filter[filter_n++] = '.';
            const uint32_t n = (uint32_t)(sp ? sp - f : strlen(f));
            memcpy(filter + filter_n, f, n), filter_n += n;
            f = (f + n + (sp ? 1 : 0));
            if (*f)
                filter[filter_n++] = ';';
        }
        filter[filter_n++] = 0;
        filter[filter_n++] = 0;

        wchar_t *filter_w = tm_unicode_api->utf8_to_utf16_n(filter, filter_n, ta);
        of.lpstrFilter = filter_w;
    }

    // We get cwd and set it afterwards because Windows changes the working directory within GetOpenFileName.
    const char *cwd = file_system_getcwd(ta);
    private__begin_modal(of.hwndOwner);
    bool gofn_res = GetOpenFileName(&of);
    private__end_modal(of.hwndOwner);
    file_system_chdir(cwd);
```

`private__begin_modal()` and `private__end_modal()` looks like this:

```
static void private__begin_modal(HWND wnd)
{
    ++os_dialog_show_count;
    const enable_windows_t args = { wnd, false, { 0 }, GetCurrentProcessId() };
    EnumWindows(private__enable_windows, (LPARAM)&args);
}

static void private__end_modal(HWND wnd)
{
    const enable_windows_t args = { wnd, true, { 0 }, GetCurrentProcessId() };
    EnumWindows(private__enable_windows, (LPARAM)&args);
}
```

Let us know if you manage to reproduce the freeze with this and figure out what's going wrong. Thanks!

**Comment by khornel** [comment] 2021-07-16 15:19
I managed to create a placeholder enable_windows_t struct and private__enable_windows callback and I removed the TM related code from the extension parsing and wrote in some constants. I also spawned an empty window to act as the hwndOwner.

I still didn't manage to freeze anything, though. That leaves virtual_memory_map, tm_sprintf, TM_LOCALIZE, tm_unicode_api->utf8_to_utf16_n, file_system_getcwd and private__enable_windows as possible culprits.

**Comment by niklas-ourmachinery** [comment] 2021-07-27 22:22
My guess (just a guess) would be that it's not a freeze in any of these functions, but rather that the freeze happens inside the `GetOpenFileName()` call... and that it is something that we do (since it doesn't happen in test code) combined with something specific for your machine (since we haven't seen it on any other machine) that causes the freeze.

Seems like people are running into similar things using Qt:

* https://www.qtcentre.org/threads/60874-QFileDialog-freezes

From googling a bit and finding people who have run into related issues, I'm suspicious about two things. First, this code:

~~~c
of.hwndOwner = GetActiveWindow();
~~~

The documentation doesn't really specify how `hwndOwner` is used... but it might be that the file dialog is waiting on that window or something. And depending on what you have installed on your machine, `GetActiveWindow()` might return something unexpected (an overlay window from an extension?).

Second, some people seem to run into issues with freezes because of COM initialization. For example this one:

* https://stackoverflow.com/questions/10809767/c-application-crashes-using-getopenfilename-dep-stops-the-crash

I notice that we don't explicitly call `CoInitializeEx()` in the `dialogs_open()` function and it's not clear to me if we need to.

Unfortunately, not having a local repro case for this makes it tricky to try out these ideas.

**Comment by niklas-ourmachinery** [comment] 2021-09-22 17:17
Maybe related to #777 ???

Perhaps we are doing something the OS doesn't like that causes issues with these dialogs... weird that it seems to happen only for a small number of users...

**Comment by niklas-ourmachinery** [comment] 2022-02-08 16:58
Closing this now for failure to replicate. @khornel are you still having this issue?

**Closed by niklas-ourmachinery** 2022-02-08 16:58 UTC
Labels: hard-to-reproduce
