### ISSUE TITLE
Visual artifacting when window is dragged off monitor

### ISSUE THREAD

**Issue by sY9sE33** [OurMachinery/themachinery-public#106] opened 2020-02-13 23:19 UTC
Dragging the window outside of a monitor causes artifacting where the window left the monitor area.

![machinery_offmonitor](https://user-images.githubusercontent.com/9271353/74487248-fa4d9d80-4e8c-11ea-97a8-b52874269932.png)

**Comment by niklas-ourmachinery** [comment] 2020-02-14 00:01
Not reproducible on my machine:

http://youtu.be/57IaTW7pX88?hd=1

**Comment by sY9sE33** [comment] 2020-02-14 00:11
I have a multi monitor setup, perhaps this is affecting it? I'm fairly certain I have the latest drivers.

I've attached a dxdiag in case something stands out.
[DxDiag.txt](https://github.com/OurMachinery/themachinery-public/files/4202032/DxDiag.txt)

**Comment by niklas-ourmachinery** [comment] 2020-02-14 00:36
I have multi-monitor setup to and can't reproduce this on any of my monitors. Maybe @tobias-ourmachinery , our rendering expert, has some insight...

**Comment by tobias-ourmachinery** [comment] 2020-02-18 16:33
The reason for this is that we are currently running the windows message pump from our "main logics job" (i.e the job responsible for ticking the entire application), and the windows API has a weird concept where the message pump might not return if it determines that the window is entering into certain states (like being resized or moved). If you watch the delta time/frame rate counter in the lower left corner you will see that it freezes when you move a window.

We might want to consider moving all window management to run as a separate task in our task system (our system for long running jobs) and provide a thread-safe `tm_os_window_api` for communicating with the main logics job. The task would need to be pinned to only be picked up and run on a certain thread as the windows API requires you to only do windows calls from the same thread that created the window (this is today handled by pinning the main logics job to a specific thread id).
 
As always dealing with the windows API is frustrating and annoying, the added complexity of making all of our `tm_os_window_api` thread-safe in a clean way might not be worth it, at least we won't prioritize it right away.. So I will close this issue for now and then we might need to revisit it in the future if this behavior feels unacceptable. 

FYI: @niklas-ourmachinery

**Closed by tobias-ourmachinery** 2020-02-18 16:33 UTC
Labels: bug
