### ISSUE TITLE
Linux: Crash when dragging the scene view

### ISSUE THREAD

**Issue by bioglaze** [OurMachinery/themachinery-public#572] opened 2021-06-04 17:25 UTC
When I drag the scene view like in the screenshot, The Machinery crashes.

![repro](https://user-images.githubusercontent.com/7099779/120839881-2bfee200-c572-11eb-93bc-c0bc54ecbb4e.png)

The error is:

```
The application encountered a fatal error and needs to shut down:

../../../plugins/vulkan_render_backend/vulkan_render_backend.c:4783
sc.num_buffers ＜ MAX_SWAP_CHAIN_BUFFERS
```

The Machinery: Beta 2021.5
OS: Ubuntu 20.04 (Gnome), all updates applied
GPU: AMD Radeon R9 Nano
Mesa: 20.2.6

Vulkaninfo:

 ```
      VkSurfaceCapabilitiesKHR:
        -------------------------
                minImageCount       = 3
                maxImageCount       = 0

```

**Comment by Hoogin** [comment] 2021-06-17 23:49
I can't reproduce this using my laptop.

OS: Slackware 15 Beta
GPU: Nvidia GeForce GT 755M (Driver: Nvidia Proprietary 460.67)

**Comment by raphael-ourmachinery** [comment] 2021-06-18 17:28
Probably the cause of this issue was the same one I had on my integrated intel card, the driver is creating more buffers than we expected but offsetting image indexes. It will be fixed on next release.

**Closed by raphael-ourmachinery** 2021-06-18 17:28 UTC
