### ISSUE TITLE
Crash when selecting an entity, when text scaling is > 100%

### ISSUE THREAD

**Issue by pbrooks** [OurMachinery/themachinery-public#367] opened 2020-11-25 09:32 UTC
To reproduce:
- Ensure the given display in windows has text scaling > 100%
- Open OM
- Click on the default "post processing stack" entity.
[the_machinery_exe 2020-11-25 09.31.57.zip](https://github.com/OurMachinery/themachinery-public/files/5595703/the_machinery_exe.2020-11-25.09.31.57.zip)

This was a crash that was introduced as of 2020.11 and still occurs on 11.a

**Comment by leonardo-ourmachinery** [comment] 2021-02-09 17:35
@pbrooks I tried really hard, but I'm unable to repro this. I've tried in many different ways, but no luck.
Could you please verify if the bug is still there?

**Comment by niklas-ourmachinery** [comment] 2021-04-23 17:54
Will close this as not reproducible because we've tried to reproduce it for several releases... if it surfaces again or if there's a better repro case, please post a new bug.

**Closed by niklas-ourmachinery** 2021-04-23 17:54 UTC
Labels: hard-to-reproduce
